#filter emptyLines

#define MOZ_LANGPACK_CREATOR aviary.pl

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Zbigniew Braniecki</em:contributor> <em:contributor>Marek Stępień</em:contributor> <em:contributor>Piotr Komoda</em:contributor> <em:contributor>Marek Wawoczny</em:contributor> <em:contributor>Piotr Bartecki</em:contributor> <em:contributor>Kornel Misiejuk</em:contributor> <em:contributor>Wadim Dziedzic</em:contributor>

#unfilter emptyLines
