#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Alexandru Szasz</em:contributor><em:contributor>Iulian Ursache-Dogariu</em:contributor><em:contributor>Cristian Brînză</em:contributor>

#unfilter emptyLines
