#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Локализација</em:contributor> <em:contributor>Новица Наков</em:contributor> <em:contributor>Дамјан Георгиевски</em:contributor> <em:contributor>Со помош од</em:contributor> <em:contributor>Георги Станојевски</em:contributor> <em:contributor>Арангел Ангов</em:contributor> <em:contributor>Владимир Стефанов</em:contributor> <em:contributor>Томислав Марковски</em:contributor> <em:contributor>Иван Стојмиров</em:contributor> <em:contributor>Игор Стаматовски</em:contributor> <em:contributor>и други</em:contributor><em:contributor>Видете mozilla.blog.com.mk</em:contributor>


#unfilter emptyLines
