#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org


# If non-English locales wish to credit multiple contributors, uncomment this


# variable definition and use the format specified.


#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>بهنام اسفهبد</em:contributor> <em:contributor>میلاد زکریا</em:contributor> <em:contributor>مسعود احمدزاده</em:contributor> <em:contributor>نیوشا بلندزاده</em:contributor> <em:contributor>روزبه پورنادر</em:contributor> <em:contributor>هوشمند حسن‌نیا</em:contributor> <em:contributor>سارا خلعت‌بری</em:contributor> <em:contributor>علیرضا خیرخواهان</em:contributor> <em:contributor>فرزانه سرافراز</em:contributor> <em:contributor>الناز سربر</em:contributor> <em:contributor>سحر فدائیان</em:contributor> <em:contributor>رضا محمدی</em:contributor>



#unfilter emptyLines
