#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Raivis Dejus</em:contributor> <em:contributor>Viesturs Zariņš</em:contributor> <em:contributor>Pēteris Krišjānis</em:contributor> <em:contributor>Citi palīgi</em:contributor>

#unfilter emptyLines
