
<script type="application/x-javascript"
        src="chrome://global/content/globalOverlay.js"/>
#ifdef XP_MACOSX
<script type="application/x-javascript"
        src="chrome://global/content/macWindowMenu.js"/>
#endif
<script type="application/x-javascript"
        src="chrome://global/content/nsDragAndDrop.js"/>
<script type="application/x-javascript"
        src="chrome://global/content/nsTransferable.js"/>
<script type="application/x-javascript"
        src="chrome://global/content/printUtils.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/util.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/domutils.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/guiutils.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/rdfutils.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/rdfmodel.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/itemtree.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/projectManager.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/project.js"/>
<script type="application/x-javascript"
        src="chrome://celtx/content/app.js"/>
