#filter emptyLines

#define MOZ_LANGPACK_CREATOR Projecto de localização do Mozilla para Português

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Artur Araújo</em:contributor> <em:contributor>Bruno Duarte</em:contributor> <em:contributor>Carlos Rodrigues</em:contributor> <em:contributor>Cláudio Esperança</em:contributor> <em:contributor>Diogo Santos</em:contributor> <em:contributor>Francisco Castanheiro</em:contributor> <em:contributor>João Miguel Neves</em:contributor> <em:contributor>Marco Sousa</em:contributor> <em:contributor>Pedro Antunes</em:contributor> <em:contributor>Pedro Figueira</em:contributor> <em:contributor>Rita Farinha</em:contributor>



#unfilter emptyLines
