#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Aleks Reinhardt</em:contributor> <em:contributor>Matjaž Horvat</em:contributor> <em:contributor>Brian King</em:contributor> <em:contributor>Martin Srebotnjak</em:contributor>

#unfilter emptyLines
