#filter emptyLines

#define MOZ_LANGPACK_CREATOR L'équipe FrenchMozilla

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Philippe Dessante</em:contributor><em:contributor>Benoît Leseul</em:contributor><em:contributor>Vincent Béron</em:contributor><em:contributor>Cédric Corazza</em:contributor><em:contributor>Marie Léger-St-Jean</em:contributor><em:contributor>Jérôme Schell</em:contributor>

#unfilter emptyLines
