#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Iago Bragado</em:contributor> <em:contributor>Vanessa Vilaverde</em:contributor> <em:contributor>Bruno Ruival</em:contributor> <em:contributor>Óscar Senra</em:contributor>

#unfilter emptyLines
